---
language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cp instance/settings.py.example instance/settings.py
script:
  - pytest
after_success: coveralls