---
language: python
python:
  - "3.5"
  - "3.6"
cache: pip
env:
  global:
    - CC_TEST_REPORTER_ID=ba4eaabdf6b35a6d0504904ba64102a7a58b746211f1eae6e9c379ea62327aa1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov
  - cp instance/settings.py.example instance/settings.py
script:
  - pytest --cov=vmailadmin
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: coveralls
