---
language: python
python: "3.8"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov
  - cp instance/settings.py.example instance/settings.py
script:
  - pytest --cov=vmailadmin
after_success: coveralls
