---
language: python
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov codeclimate-test-reporter
  - cp instance/settings.py.example instance/settings.py
script:
  - pytest --cov=vmailadmin
  - codeclimate-test-reporter --file .coverage
after_success: coveralls
