"""add deniedrecipients

Revision ID: 27b7cf4464fc
Revises: 4a6f36d1ea1c
Create Date: 2023-08-01 22:14:55.026808

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '27b7cf4464fc'
down_revision = '4a6f36d1ea1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deniedrecipients',
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('domain', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('username', 'domain'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deniedrecipients')
    # ### end Alembic commands ###
