"""initial

Revision ID: 4a6f36d1ea1c
Revises:
Create Date: 2023-08-01 22:14:26.321357

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4a6f36d1ea1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('domain', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('sendonly', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('username', 'domain'),
    )
    op.create_table(
        'aliases',
        sa.Column('address', sa.String(length=320), nullable=False),
        sa.Column('goto', sa.String(length=320), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('address'),
    )
    op.create_table(
        'domains',
        sa.Column('domain', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('domain'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domains')
    op.drop_table('aliases')
    op.drop_table('accounts')
    # ### end Alembic commands ###
